# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a17adeaa05bde530e1bed14f18d00a25d448e8038f167463eab2b4ff599e0713e901517b7260e1562a76f3eab230ab1def4422c4b66c2a4dc3a2a3aca85582b8

test:
  secret_key_base: d35e66433698cd687fecc6e2eab0223958957f6ddc96807958faae249f562a773a0b1309d08676babe0fe80a6810c19684a0c6c898595be96205bf43f9d1caf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
